accent = "#737174"
cursor = "#fcef0c"
foreground = "#dadbd6"
background = "#1b1d1e"
selection_foreground = "#dadbd6"
selection_background = "#737174"

color0 = "#505354"
color1 = "#e6dc44"
color2 = "#c8be46"
color3 = "#f4fd22"
color4 = "#737174"
color5 = "#747271"
color6 = "#62605f"
color7 = "#c6c5bf"
color8 = "#a3a3a6"
color9 = "#fff78e"
color10 = "#fff27d"
color11 = "#feed6c"
color12 = "#919495"
color13 = "#9a9a9d"
color14 = "#a3a3a6"
color15 = "#dadbd6"
